name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup-ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz -o ffmpeg-git-amd64-static.tar.xz
      - run: tar xf ffmpeg-git-amd64-static.tar.xz
      - run: cp ffmpeg-*-static/{ffmpeg,ffprobe} .
      - run: rm -rf ffmpeg-*-static
      - run: actions/upload-artifact@v2
        with:
          name: ffmpeg-git
          path: |
            ffmpeg
            ffprobe

  test:
    needs: setup-ffmpeg

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@v2
        with:
          name: ffmpeg-git
          path: ffmpeg
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
        env:
          FFMPEG_PATH: ffmpeg/ffmpeg
          FFPROBE_PATH: ffmpeg/ffprobe
