name: tests

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [master]
    paths-ignore:
      - '**/*.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # Build and test on all LTS releases
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # This action installs ffmpeg
      - uses: FedericoCarboni/setup-ffmpeg@v1-beta
        id: setup-ffmpeg
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
        env:
          FFMPEG_PATH: ${{ steps.setup-ffmpeg.outputs.ffmpeg-path }}
          FFPROBE_PATH: ${{ steps.setup-ffmpeg.outputs.ffprobe-path }}
      # Upload coverage to codecov.io
      - run: npm run coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
